name: $hyoo_sync_server

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: hyoo-ru/mam_build@master2
      with:
        token: ${{ secrets.GH_PAT }}
        package: 'hyoo/sync'
        modules: 'server watch auth'
    
    - run: 'cp -r hyoo/sync/watch/- hyoo/sync/server/-/watch'
    - run: 'cp -r hyoo/sync/auth/- hyoo/sync/server/-/auth'
    
    - uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      if: github.ref == 'refs/heads/master'
      with:
        repo-token: ${{ secrets.GH_PAT }}
        site-directory: 'hyoo/sync/server/-'
